from django.urls import path
from django.views.generic import TemplateView
from .import views

app_name = "green"

urlpatterns = [
    path("",views.home, name="home.html"),
    path("Basica_Matematicas_primero/",views.m1, name="Basica_Matematicas_primero"),
    path("Basica_Lenguaje_primero/",views.l1, name="Basica_Lenguaje_primero"),
    path("Basica_Ciencias_primero/",views.c1, name="Basica_Ciencias_primero"),
    path("Basica_Historia_primero/",views.h1, name="Basica_Historia_primero"),
    path("Basica_Otros_primero/",views.o1, name="Basica_Otros_primero"),
    path("Basica_Ingles_primero/",views.i1, name="Basica_Ingles_primero"),
    path("Basica_Matematicas_segundo/",views.m2, name="Basica_Matematicas_segundo"),
    path("Basica_Lenguaje_segundo/",views.l2, name="Basica_Lenguaje_segundo"),
    path("Basica_Ciencias_segundo/",views.c2, name="Basica_Ciencias_segundo"),
    path("Basica_Historia_segundo/",views.h2, name="Basica_Historia_segundo"),
    path("Basica_Otros_segundo/",views.o2, name="Basica_Otros_segundo"),
    path("Basica_Ingles_segundo/",views.i2, name="Basica_Ingles_segundo"),
    path("Basica_Matematicas_tercero/",views.m3, name="Basica_Matematicas_tercero"),
    path("Basica_Lenguaje_tercero/",views.l3, name="Basica_Lenguaje_tercero"),
    path("Basica_Ciencias_tercero/",views.c3, name="Basica_Ciencias_tercero"),
    path("Basica_Historia_tercero/",views.h3, name="Basica_Historia_tercero"),
    path("Basica_Otros_tercero/",views.o3, name="Basica_Otros_tercero"),
    path("Basica_Ingles_tercero/",views.i3, name="Basica_Ingles_tercero"),
    path("Basica_Matematicas_cuarto/",views.m4, name="Basica_Matematicas_cuarto"),
    path("Basica_Lenguaje_cuarto/",views.l4, name="Basica_Lenguaje_cuarto"),
    path("Basica_Ciencias_cuarto/",views.c4, name="Basica_Ciencias_cuarto"),
    path("Basica_Historia_cuarto/",views.h4, name="Basica_Historia_cuarto"),
    path("Basica_Otros_cuarto/",views.o4, name="Basica_Otros_cuarto"),
    path("Basica_Ingles_cuarto/",views.i4, name="Basica_Ingles_cuarto"),
    path("Basica_Matematicas_quinto/",views.m5, name="Basica_Matematicas_quinto"),
    path("Basica_Lenguaje_quinto/",views.l5, name="Basica_Lenguaje_quinto"),
    path("Basica_Ciencias_quinto/",views.c5, name="Basica_Ciencias_quinto"),
    path("Basica_Historia_quinto/",views.h5, name="Basica_Historia_quinto"),
    path("Basica_Otros_quinto/",views.o5, name="Basica_Otros_quinto"),
    path("Basica_Ingles_quinto/",views.i5, name="Basica_Ingles_quinto"),
    path("Basica_Matematicas_sexto/",views.m6, name="Basica_Matematicas_sexto"),
    path("Basica_Lenguaje_sexto/",views.l6, name="Basica_Lenguaje_sexto"),
    path("Basica_Ciencias_sexto/",views.c6, name="Basica_Ciencias_sexto"),
    path("Basica_Historia_sexto/",views.h6, name="Basica_Historia_sexto"),
    path("Basica_Otros_sexto/",views.o6, name="Basica_Otros_sexto"),
    path("Basica_Ingles_sexto/",views.i6, name="Basica_Ingles_sexto"),
    path("Basica_Matematicas_septimo/",views.m7, name="Basica_Matematicas_septimo"),
    path("Basica_Lenguaje_septimo/",views.l7, name="Basica_Lenguaje_septimo"),
    path("Basica_Ciencias_septimo/",views.c7, name="Basica_Ciencias_septimo"),
    path("Basica_Historia_septimo/",views.h7, name="Basica_Historia_septimo"),
    path("Basica_Otros_septimo/",views.o7, name="Basica_Otros_septimo"),
    path("Basica_Ingles_septimo/",views.i7, name="Basica_Ingles_septimo"),
    path("Basica_Matematicas_octavo/",views.m8, name="Basica_Matematicas_octavo"),
    path("Basica_Lenguaje_octavo/",views.l8, name="Basica_Lenguaje_octavo"),
    path("Basica_Ciencias_octavo/",views.c8, name="Basica_Ciencias_octavo"),
    path("Basica_Historia_octavo/",views.h8, name="Basica_Historia_octavo"),
    path("Basica_Otros_octavo/",views.o8, name="Basica_Otros_octavo"),
    path("Basica_Ingles_octavo/",views.i8, name="Basica_Ingles_octavo"),
    path('post/', views.create_post, name= 'create-post'),
]
